---
# http web server
http:
   address: http://localhost
   port: 2000
   content: content
# CPU profiling
cpu:
   enabled: false
   filename: cpu.pprof
# memory profiling
memory:
   enabled: true
   filename: memory.mprof
